apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: part1
spec:
  type: NodePort
  ports:
    - name: pgadmin
      port: 80
      targetPort: 80
      nodePort: 32555
  selector:
    app: pgadmin
