kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: part1
  name: pgadmin-pv-part1
  labels:
    type: local
    app: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pgadmin-part1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pvc-part1
  namespace: part1
  labels:
    app: pgadmin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

