kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: part1
  name: postgres-pv-part1
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pg-part1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc-part1
  namespace: part1
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

